# Generated by Django 4.2.7 on 2025-07-02 04:26

from django.db import migrations
import reading.models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', reading.models.CustomUserManager()),
            ],
        ),
    ]
